# Generated by Django 5.0.7 on 2024-07-31 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_aimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='regdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=25)),
                ('Lastname', models.CharField(max_length=25)),
                ('Email', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='img/%y')),
                ('status', models.BooleanField(default=False, help_text='0-show , 1-Hidden')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('vendor', models.CharField(max_length=100)),
                ('prod_image', models.ImageField(upload_to='img/%y')),
                ('quantity', models.IntegerField()),
                ('original_price', models.IntegerField()),
                ('off_price', models.IntegerField()),
                ('description', models.TextField(max_length=450)),
                ('trending', models.BooleanField(default=False, help_text='0-show , 1-Hidden')),
                ('status', models.BooleanField(default=False, help_text='0-show , 1-Hidden')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.shop')),
            ],
        ),
    ]
