# Generated by Django 5.0.7 on 2024-07-31 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_regdata_shop_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='subcategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='img/%y')),
                ('status', models.BooleanField(default=False, help_text='0-show , 1-Hidden')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
