# Generated by Django 5.0.7 on 2024-07-31 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_subcategories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='subcategories',
        ),
    ]
