# Generated by Django 5.0.7 on 2024-08-01 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_subcategories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='products',
        ),
    ]
