# Generated by Django 5.0.7 on 2024-08-01 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_delete_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='subcategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='img/%y')),
                ('status', models.BooleanField(default=False, help_text='0-show , 1-Hidden')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.shop')),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('vendor', models.CharField(max_length=100)),
                ('prod_image', models.ImageField(upload_to='img/%y')),
                ('quantity', models.IntegerField()),
                ('original_price', models.IntegerField()),
                ('off_price', models.IntegerField()),
                ('description', models.TextField(max_length=450)),
                ('trending', models.BooleanField(default=False, help_text='0-show , 1-Hidden')),
                ('status', models.BooleanField(default=False, help_text='0-show , 1-Hidden')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subcategories')),
            ],
        ),
    ]
