# Generated by Django 5.0.7 on 2024-08-01 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_subcategories_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategories',
            name='subcategory',
        ),
        migrations.DeleteModel(
            name='products',
        ),
        migrations.DeleteModel(
            name='shop',
        ),
        migrations.DeleteModel(
            name='subcategories',
        ),
    ]
