# Generated by Django 5.0.7 on 2024-08-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_shop_subcategories_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='wishlist',
            field=models.BooleanField(default=False, help_text='0-show , 1-Hidden'),
        ),
    ]
